name:              Devon Mitton
description:       Designer
url:               http://devonmitton.com

encoding:          UTF-8
source:            _src
destination:       _build
permalink:         pretty

include:           [".htaccess"]
exclude:           ["README.md"]

excerpt_separator: "<!-- more -->"

sass:
  sass_dir:        /assets/stylesheets/
  style:           compressed

gems:
  - octopress-autoprefixer
  - jekyll-contentblocks

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      categories: "writing"
      bodyclass: "single-post"
